"""
Generate catalog.json, docs/catalog.md, and the README tree snippet.

- Scans for PDF files under the repo (excluding .git and docs).
- Merges with existing catalog.json to preserve summaries/tags.
- Writes updated catalog.json sorted by path.
- Renders a full catalog to docs/catalog.md with summaries.
- Refreshes the README tree section (top-level + second-level folders).

Usage:
  python scripts/build_catalog.py
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parents[1]
CATALOG_JSON = ROOT / "catalog.json"
CATALOG_MD = ROOT / "docs" / "catalog.md"
CATALOG_MD_ROOT = ROOT / "catalog.md"
TREE_MD = ROOT / "docs" / "tree.md"
TREE_MD_ROOT = ROOT / "tree.md"
README = ROOT / "README.md"

TREE_START = "<!-- TREE-START -->"
TREE_END = "<!-- TREE-END -->"


def scan_pdfs(root: Path) -> List[Path]:
    pdfs: List[Path] = []
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() != ".pdf":
            continue
        if ".git" in path.parts or path.parts[0] == "docs":
            continue
        pdfs.append(path.relative_to(root))
    return sorted(pdfs)


def load_catalog() -> Dict[str, Dict]:
    if not CATALOG_JSON.exists():
        return {}
    return {entry["path"]: entry for entry in json.loads(CATALOG_JSON.read_text())}


def build_catalog_entries(pdfs: List[Path], existing: Dict[str, Dict]) -> List[Dict]:
    entries = []
    for path in pdfs:
        key = str(path)
        prev = existing.get(key, {})
        entry = {
            "path": key,
            "title": prev.get("title") or path.stem,
            "summary": prev.get("summary", ""),
            "tags": prev.get("tags", []),
        }
        entries.append(entry)
    return sorted(entries, key=lambda e: e["path"])


def save_catalog(entries: List[Dict]) -> None:
    CATALOG_JSON.parent.mkdir(parents=True, exist_ok=True)
    CATALOG_JSON.write_text(json.dumps(entries, indent=2))


def build_tree(paths: List[Path]) -> Dict:
    tree: Dict = {}
    for path in paths:
        node = tree
        parts = list(path.parts)
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node.setdefault("_files", []).append(parts[-1])
    return tree


def render_tree(tree: Dict, max_depth: int | None = None, depth: int = 0) -> List[str]:
    lines: List[str] = []
    for folder in sorted([k for k in tree.keys() if k != "_files"]):
        prefix = "  " * depth + "- "
        lines.append(f"{prefix}{folder}/")
        if max_depth is None or depth + 1 < max_depth:
            lines.extend(render_tree(tree[folder], max_depth=max_depth, depth=depth + 1))
    if "_files" in tree and (max_depth is None or depth < max_depth):
        for f in sorted(tree["_files"]):
            prefix = "  " * depth + "- "
            lines.append(f"{prefix}`{f}`")
    return lines


def render_catalog_md(entries: List[Dict]) -> str:
    lines = [
        "# Papers Catalog",
        "",
        "_Auto-generated by `scripts/build_catalog.py`. Edit summaries in `catalog.json`._",
        "",
        "## Files",
        "",
    ]
    for entry in entries:
        summary = entry["summary"].strip() or "_(add summary)_"
        lines.append(f"- `{entry['path']}` — **{entry['title']}** — {summary}")
    lines.append("")
    return "\n".join(lines)


def render_tree_md(tree_lines: List[str]) -> str:
    lines = [
        "# Papers Tree",
        "",
        "_Auto-generated by `scripts/build_catalog.py`. Full repository tree for PDFs._",
        "",
    ]
    lines.extend(tree_lines)
    lines.append("")
    return "\n".join(lines)


def update_readme(tree_lines: List[str]) -> None:
    content = README.read_text()
    tree_block = "\n".join(tree_lines)
    snippet = (
        "## Repo Tree (snapshot)\n"
        f"{TREE_START}\n{tree_block}\n{TREE_END}\n"
        "See full catalog: catalog.md\n"
        "See full tree: tree.md\n"
    )

    if TREE_START in content and TREE_END in content:
        before, rest = content.split(TREE_START, 1)
        _, after = rest.split(TREE_END, 1)
        new_content = before.rstrip() + snippet + after
    else:
        new_content = content.rstrip() + "\n\n" + snippet + "\n"
    README.write_text(new_content)


def main() -> None:
    pdfs = scan_pdfs(ROOT)
    existing = load_catalog()
    entries = build_catalog_entries(pdfs, existing)
    save_catalog(entries)

    tree = build_tree(pdfs)
    tree_lines = render_tree(tree, max_depth=2)
    tree_lines_full = render_tree(tree)

    catalog_md_content = render_catalog_md(entries)
    tree_md_content = render_tree_md(tree_lines_full)

    # Write catalog and tree both to docs/ and repo root for easier discovery.
    for path in (CATALOG_MD, CATALOG_MD_ROOT):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(catalog_md_content)

    for path in (TREE_MD, TREE_MD_ROOT):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(tree_md_content)

    update_readme(tree_lines)


if __name__ == "__main__":
    main()
